/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.three.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;

import java.util.Objects;

/**
 * Branches
 */

public class BranchesDistance {

  @JsonProperty("id")
  private Long id = null;
  @JsonProperty("title")
  private String title = null;
  @JsonProperty("lon")
  private Double lon = null;
  @JsonProperty("lat")
  private Double lat = null;
  @JsonProperty("address")
  private String address = null;
  @JsonProperty("distance")
  @Getter
  @Setter
  private long distance = 0L;

  public BranchesDistance address(String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   *
   * @return address
   **/
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public BranchesDistance id(Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   *
   * @return id
   **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public BranchesDistance lat(Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * Get lat
   *
   * @return lat
   **/
  public Double getLat() {
    return lat;
  }

  public void setLat(Double lat) {
    this.lat = lat;
  }

  public BranchesDistance lon(Double lon) {
    this.lon = lon;
    return this;
  }

  /**
   * Get lon
   *
   * @return lon
   **/
  public Double getLon() {
    return lon;
  }

  public void setLon(Double lon) {
    this.lon = lon;
  }

  public BranchesDistance title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Get title
   *
   * @return title
   **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BranchesDistance branches = (BranchesDistance) o;
    return Objects.equals(this.address, branches.address) &&
        Objects.equals(this.id, branches.id) &&
        Objects.equals(this.lat, branches.lat) &&
        Objects.equals(this.lon, branches.lon) &&
        Objects.equals(this.title, branches.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, id, lat, lon, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Branches {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

